version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build: .
    container_name: library-management-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - library-network

  db:
    image: postgres:16-alpine
    container_name: library-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  postgres_data: