server:
  port: 8080

spring:
  application:
    name: LibraryManagementSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: Z2V0aXJCb290Y2FtcC1maW5hbENhc2UubXlzZWNyZXRLZXkyMDI1
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security: DEBUG


springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha